sudo: required
dist: trusty
language: java
script:
- gradle -b lang/java/build.gradle check
- sh run.sh
- gradle -b demo/java/build.gradle check
before_install:
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq

install:
- sudo apt-get -yqq install g++-4.8
- export CXX="g++-4.8"
- sh install_dep.sh
- sudo apt-get -yqq install libboost-filesystem1.54-dev
- sudo apt-get -yqq install libboost-program-options1.54-dev
- sudo apt-get -yqq install bison flex